# Generated by Django 3.0.7 on 2020-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcity',
            name='cityName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
